spring:
    server:
        port : 8080        
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3306/react_board_test
        username: reactUserTester
        password: 4682